import React, { Component, useContext, useEffect, useState } from 'react' ;
import { Text, View, Button, StyleSheet } from 'react-native' ;
import {Button as PaperButton, RadioButton } from 'react-native-paper' ;
import  TranslateText  from '../components/TranslateText' ;
import { SettingsContext } from '../components/SettingsContext' ;

export async function translateRequest(value:string, target: string){
    let fromLang = 'en';        // source lsang to translate from ( default is English )
    let toLang = target;        // target lang to translate to
    let text = value;           // string to translate to toLang

    const API_KEY = 'AIzaSyAdZc_5KMyqTZDjxndb6w61gBmREomVT2o';                           // API key generated by GCP https://console.cloud.google.com/apis/credentials?project=sdp-mmg
    
    let url = `https://translation.googleapis.com/language/translate/v2?key=${API_KEY}`; // Build url string to send GET Request to GCP
    url += '&q=' + encodeURI(text);
    url += `&source=${fromLang}`;
    url += `&target=${toLang}`;
    
    console.log('')
    console.log('')
    console.log ('GET Request url is ' , url);              // Log the GET Request url

    try {                                                   // Try to fetch GET Request from Google Translat, then return the translated string to the callee
        const response = await fetch(url, {                         
            method: 'GET',
            headers: {
              "Content-Type": "application/json",
              Accept: "application/json"
            }
          })
        const parsed = await response.json();               // Parse the response to a JSON and await the response
        return parsed.data.translations[0].translatedText;  // Return the translated string
    } catch (error) {
        // Error fetching translation or parsing the response
        console.error("Error Translating Text: Validate GET Request url and parsed response are correct.")
    }
};

export function handleEngChange(checked:any,setChecked:any){
    const { changeLangToEn } = React.useContext(SettingsContext);
    changeLangToEn()
    setChecked(checked)
}

export function handleEsChange(checked:any,setChecked:any){
    const { changeLangToEs } = React.useContext(SettingsContext);
    changeLangToEs
    return (setChecked(checked))
}

export function handleFrChange(checked:any,setChecked:any){
    const { changeLangToFr } = React.useContext(SettingsContext);
    changeLangToFr
    return (setChecked(checked))
}

export default function LanguageSelectionScreen(this: any, {navigation} : {navigation: any}) {
    const image = { uri: "https://wallpaperaccess.com/full/1954699.jpg" };
    let [_checked, setChecked] = React.useState('en');

    const { currentLang_, changeLangToEn, changeLangToEs, changeLangToFr} = React.useContext(SettingsContext);

    return (
        <View style={styles.container}>
            <Text style={styles.greeting}>
                <TranslateText text="Welcome to TCU's Monnig Meteorite Gallery!" lang={currentLang_}/>
            </Text>
            
            <Text style={styles.header}> 
                <TranslateText text="Please select your language preference" lang={currentLang_}/>
            </Text>

                <View style={{alignSelf: 'center', width: "35%"}}>
                    <RadioButton.Item labelStyle={{fontSize: 32, fontFamily: 'ROBOTO', width: "50%"}}
                        value="en" color="#4D1979" label="English" status={ _checked === 'en' ? 'checked' : 'unchecked'} onPress={() => 
                        {
                            changeLangToEn()
                            setChecked('en')
                        }}/>
                    <RadioButton.Item labelStyle={{fontSize: 32, fontFamily: 'ROBOTO', width: "50%"}}
                        value="es" color="#4D1979" label="Spanish" status={ _checked === 'es' ? 'checked' : 'unchecked'} onPress={() => 
                        {
                            changeLangToEs()
                            setChecked('es')
                        }}/>
                    <RadioButton.Item labelStyle={{fontSize: 32, fontFamily: 'ROBOTO', width: "50%"}}
                        value="fr" color="#4D1979" label="French" status={ _checked === 'fr' ? 'checked' : 'unchecked'} onPress={() => 
                        {
                            changeLangToFr()
                            setChecked('fr')
                        }}/>
                </View>
            <View style={styles.continueButton}>
                <PaperButton mode="contained" onPress={() => navigation.navigate('AcuityScreen')}><TranslateText text="Continue" lang={currentLang_}/></PaperButton>
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
    },
    radioContainer: {
        flex: 1,
      },
    image: {
        width: "100%",
        flex: 1,
        justifyContent: "center"
    },
    greeting: {
        textAlign: "center",
        height: "20%",
        fontSize: 38,
        paddingTop: "10%",
        fontFamily: "Rationale"
    },
    header: {
        textAlign: "center",
        height: "15%",
        fontSize: 32
    },
    continueButton: {
        flex: 1,
        marginTop: 250,
        marginBottom: 50,
        width: "45%",
        alignSelf: 'center',
        bottom:0
    }
});
